# Generated by Django 4.1.13 on 2025-07-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='justification_file',
            field=models.FileField(blank=True, help_text='Fichier justificatif', null=True, upload_to='justificatifs/'),
        ),
        migrations.AddField(
            model_name='retard',
            name='justification_file',
            field=models.FileField(blank=True, help_text='Fichier justificatif', null=True, upload_to='justificatifs/'),
        ),
    ]
