# Generated by Django 4.1.13 on 2025-07-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biometric_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID biométrique (empreinte)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif (non archivé)'),
        ),
    ]
